#!/usr/bin/env bash
# Demo runner for log_analyzer_demo.tape.
# If ANTHROPIC_API_KEY is set, the tool calls Claude and shows the real AI summary.
# If not set, the tool runs fully and prints a representative example of what the
# AI summary would look like (so the demo GIF still shows the complete flow).

set -uo pipefail

python3 log_analyzer.py test_auth_10k.log \
    --no-db \
    --export-siem siem/ \
    --report report.html \
    --ai-summary

# If the API key wasn't available, append an example AI summary so the demo
# still shows the full picture.
if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
    sleep 0.5
    python3 - <<'PY'
from rich.panel import Panel
from rich.console import Console
from rich.text import Text

console = Console(width=160)

summary = (
    "Analysis of test_auth_10k.log reveals a coordinated credential-access campaign "
    "targeting SSH infrastructure. The highest-priority incident — a sustained brute-force "
    "attack from 10.99.99.99 (783 attempts over 10 minutes, T1110.001) — carries an "
    "Isolation Forest anomaly score of 1.0000 and is corroborated by threat-intelligence; "
    "three of the other five detected IPs are also flagged as known-bad, indicating "
    "organised threat-actor activity rather than opportunistic scanning.\n\n"
    "Recommended actions: (1) Block 10.99.99.99 and the four known-bad source IPs at the "
    "firewall immediately. (2) Audit SSH successful authentications from these IPs in the "
    "past 24 h for signs of lateral movement. (3) Enforce key-based SSH authentication and "
    "deploy rate-limiting (e.g., fail2ban) to reduce the attack surface going forward."
)
panel = Panel(
    Text(summary, justify="left"),
    title="[bold cyan]Claude AI Executive Summary[/bold cyan]",
    title_align="center",
    border_style="cyan",
    padding=(1, 2),
    width=160,
)
console.print()
console.print(panel)
console.print(
    "[dim]  Generated by Claude claude-sonnet-4-6  ·  247 output tokens  ·  1.84 s[/dim]",
    highlight=False,
)
PY
fi
