"""Tests for native SIEM query compilation (pySigma backends)."""
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

siem_export = pytest.importorskip("siem_export")


def test_brute_force_compiles_to_all_three_siems():
    q = siem_export.incident_to_queries("brute_force")
    assert set(q) == {"splunk", "esql", "sentinel"}
    # event_count aggregation + threshold show up in every dialect.
    assert "stats count as event_count" in q["splunk"]
    assert "src_ip" in q["splunk"]                      # Splunk CIM field
    assert "event_count >= 5" in q["splunk"]
    assert "count()" in q["esql"] and "source.ip" in q["esql"]   # ECS field
    assert "summarize event_count = count()" in q["sentinel"]
    assert "SrcIpAddr" in q["sentinel"]                 # Sentinel ASIM field


def test_port_scan_uses_distinct_port_count():
    q = siem_export.incident_to_queries("port_scan")
    assert "dc(dest_port)" in q["splunk"]               # distinct dest ports
    assert "count_distinct(destination.port)" in q["esql"]
    assert "dcount(DstPortNumber)" in q["sentinel"]
    assert "value_count >= 20" in q["splunk"]


def test_flood_404_threshold():
    q = siem_export.incident_to_queries("flood_404")
    for dialect in q.values():
        assert ">= 30" in dialect


def test_unknown_incident_returns_none():
    assert siem_export.incident_to_queries("nonsense") is None


def test_export_siem_writes_three_files_per_type(tmp_path):
    incidents = [
        {"incident_type": "brute_force", "source_ip": "10.0.0.1"},
        {"incident_type": "brute_force", "source_ip": "10.0.0.2"},  # dedup
        {"incident_type": "flood_404", "source_ip": "203.0.113.7"},
    ]
    paths = siem_export.export_siem(incidents, str(tmp_path))
    # 2 unique types x 3 SIEM targets = 6 files.
    assert len(paths) == 6
    written = {os.path.basename(p) for p in paths}
    assert {"brute_force.spl", "brute_force.esql", "brute_force.kql"} <= written
    assert {"flood_404.spl", "flood_404.esql", "flood_404.kql"} <= written
    # Files are non-empty and carry the language banner comment.
    for p in paths:
        text = open(p).read()
        assert text.strip() and "generated by log-analyzer" in text
