# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ingest.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ingest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cingest.proto\x12\rsoc.ingest.v1\"\xae\x01\n\x12IngestAlertRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x11\n\tsource_ip\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x17\n\x0fworkflow_run_id\x18\x07 \x01(\t\x12\x14\n\x0crun_metadata\x18\x08 \x01(\t\"W\n\x13IngestAlertResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t2j\n\x12\x41lertIngestService\x12T\n\x0bIngestAlert\x12!.soc.ingest.v1.IngestAlertRequest\x1a\".soc.ingest.v1.IngestAlertResponseB6Z4github.com/Romil2112/SOC-Dashboard/internal/ingestpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/Romil2112/SOC-Dashboard/internal/ingestpb'
  _globals['_INGESTALERTREQUEST']._serialized_start=32
  _globals['_INGESTALERTREQUEST']._serialized_end=206
  _globals['_INGESTALERTRESPONSE']._serialized_start=208
  _globals['_INGESTALERTRESPONSE']._serialized_end=295
  _globals['_ALERTINGESTSERVICE']._serialized_start=297
  _globals['_ALERTINGESTSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
