# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ingest_pb2 as ingest__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlertIngestServiceStub:
    """AlertIngestService is the high-throughput write path for pushing security
    alerts into the SOC Dashboard. Both REST (port 8001) and gRPC (port 9001)
    transports are served by the same underlying service implementation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestAlert = channel.unary_unary(
                '/soc.ingest.v1.AlertIngestService/IngestAlert',
                request_serializer=ingest__pb2.IngestAlertRequest.SerializeToString,
                response_deserializer=ingest__pb2.IngestAlertResponse.FromString,
                _registered_method=True)


class AlertIngestServiceServicer:
    """AlertIngestService is the high-throughput write path for pushing security
    alerts into the SOC Dashboard. Both REST (port 8001) and gRPC (port 9001)
    transports are served by the same underlying service implementation.
    """

    def IngestAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertIngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestAlert,
                    request_deserializer=ingest__pb2.IngestAlertRequest.FromString,
                    response_serializer=ingest__pb2.IngestAlertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'soc.ingest.v1.AlertIngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('soc.ingest.v1.AlertIngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlertIngestService:
    """AlertIngestService is the high-throughput write path for pushing security
    alerts into the SOC Dashboard. Both REST (port 8001) and gRPC (port 9001)
    transports are served by the same underlying service implementation.
    """

    @staticmethod
    def IngestAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soc.ingest.v1.AlertIngestService/IngestAlert',
            ingest__pb2.IngestAlertRequest.SerializeToString,
            ingest__pb2.IngestAlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
