apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "soc-stack.fullname" . }}-soc-dashboard
  namespace: security-tools
  labels:
    {{- include "soc-stack.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "soc-stack.fullname" . }}-soc-dashboard
  minReplicas: {{ .Values.socDashboard.replicaCount }}
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
